name: Generate Snake and Pacman

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake animation
        uses: Platane/snk@master
        with:
          github_user_name: pundirdiya898
          outputs: |
            dist/snake.svg
            dist/pacman-contribution-graph.svg
            dist/pacman-contribution-graph-dark.svg
          
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
